# Documentation relevant to this build configuration file:
#
# https://docs.travis-ci.com/user/languages/java/

language: java

# Travis provides different sets of JDKs for different Ubuntu distributions:
#
# https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks

matrix:
  include:
#    - os: linux
#      dist: precise
#      jdk: openjdk6
    - os: linux
      dist: precise
      jdk: oraclejdk7
    - os: linux
      dist: trusty
      jdk: openjdk7
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk9
    - os: linux
      dist: bionic
      jdk: openjdk10
    - os: linux
      dist: bionic
      jdk: openjdk11

install: mvn install -DskipTests=true -Dgpg.skip=true

script:
  - mvn clean verify -Dgpg.skip=true

after_success:
  - mvn -Pcoverage clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
